### ISSUE TITLE
Blob types

### ISSUE THREAD

**Issue by ktonon** [ktonon/aws-sdk-elm#2]
See `resolve-types.js`, the `resolve.blob` function. Currently it is set to the same as `string`, but should map to some other elm type, either from core or otherwise.

We will need a decoder too

**Comment by ktonon** [comment]
Never worked with projects on github before. Just figured out that we can convert cards into issues, which is nice. So we can assign to determine ownership, instead of using columns. I'll change the columns in the projects to read `Triage`, `Todo`, `In Progress`, and `Complete`

**Comment by nickmonad** [comment]
https://groups.google.com/forum/#!topic/elm-discuss/spr621OlUeo

**Comment by nickmonad** [comment]
https://groups.google.com/forum/#!topic/elm-discuss/g65pRzgqkvo

**Comment by ktonon** [comment]
Good finds, the last post on the second link looks useful, maybe for auth too

**Comment by nickmonad** [comment]
@ktonon Since there some cases in which [JSON](http://docs.aws.amazon.com/lambda/latest/dg/API_ListFunctions.html) is returned from a service call, and others in which [raw content](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html) is returned (see `Sample Response`), we may have to get creative with decoders. I've been looking into the `Json.Decode` and `Http` implementations, and it seems like we should be able to read the entire body (in the raw content case) and compose that into some other decoder that wraps it into a higher level struct with a `Body` field. Although, it may require a native module, taking some cues from `elm-lang/core`.

This means we'll also need a way to parameterize the `expect` field of a request.

**Comment by ktonon** [comment]
do you think this might be useful? Haven't looked at it in detail: https://github.com/jinjor/elm-binary-decoder

**Comment by nickmonad** [comment]
Ah, very nice. I will definitely give that a shot

**Comment by ktonon** [comment]
Closing all issues as this project is deprecated
